# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            wilson ryan
tagline:          Electrical and Embedded Audio Engineer

url:              http://www.wilsonryan.com
baseurl:          /

author:
  name:           'Wilson Ryan'

paginate:         5

# Custom vars
# version:          2.1.0

# github:           https://github.com/quailson
#  repo:           https://github.com/poole/hyde
